name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt

  download:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    #- name: Create dir
    #  run: mkdir ./artifacts

    - name: Donwload text file
      uses: actions/download-artifact@v4
      with:
        name: hello-artifact
        path: artifacts/
    - name: Ls
      run: ls -latr artifacts

    - name: Display hello.txt
      run: cat ./artifacts/hello.txt